Tests or array::intersects()
sanity-io/groq-test-suite pull request #80
Opened 2024-03-29 20:50 UTC by atombender

2024-04-08 07:53 UTC, judofyr requested changes
Some of the variables here are not valid JSON (since they include `dateTime`/`geo`) and this means that the built-in [Automatic test generation based on variables](https://github.com/sanity-io/groq-test-suite#automatic-test-generation-based-on-variables) doesn't kick in. With the changes proposed here we get a bunch of more tests generated.

---

As an aside, we really should re-think the whole "if a variable is JSON then parse it" thingie. It's probably a lot clearer if we do the opposite: The test case contains the JSON, and then we instead serialize it into the query:

```yml
generate:
  variables:
    expr: [1, "1", null, true, false, {"a": 42}]
```

This could then also assert that there is no `documents` (which is another gotcha!)

I think also @rneatherway was a bit surprised as to how the same variable duplicated in a query behaved.

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +name: "array::intersects() function"
```suggestion
name: "array::intersects() function"
version: ">= 1.2"
```

This needs a version for the test runners to actually run this test.

2024-04-08 07:53 UTC, judofyr commented on test/misc/subqueries.yml
> -  - name: "sunquery-union"
🌞

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +    lit: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1})]'
```suggestion
    lit: '[1, "1", null, true, false, {"a": 42}]'
```

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +      arr: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1})]'
```suggestion
      arr: '[1, "1", null, true, false, {"a": 42}]'
```

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +      arr: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1}), "2"]'
```suggestion
      arr: '[1, "1", null, true, false, {"a": 42}, "2"]'
```

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +    lit: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1})]'
```suggestion
    lit: '[1, "1", null, true, false, {"a": 42}]'
```

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +      arr: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1})]'
```suggestion
      arr: '[1, "1", null, true, false, {"a": 42}]'
```

2024-04-08 07:53 UTC, judofyr commented on test/function/array-intersects.yml
> +      arr: '[1, "1", null, true, false, dateTime("2002-10-02T12:34:56Z"), {"a": 42}, geo({"lat": 1, "lng": 1}), "2"]'
```suggestion
      arr: '[1, "1", null, true, false, {"a": 42}, "2"]'
```

2024-05-07 22:36 UTC, atombender commented
Any comment on the above?

2024-05-21 19:43 UTC, atombender commented
@judofyr Another bump. 🙂

2024-05-22 09:07 UTC, judofyr commented
Separate `dateTime` / `geo` tests sounds perfectly fine to me. They are quite different beasts. We're already lacking tests which checks that `array::intersects` with the _same_ `dateTime` / `geo` returns `false`.

2024-05-31 08:50 UTC, atombender commented
> They are quite different beasts. We're already lacking tests which checks that `array::intersects` with the _same_ `dateTime` / `geo` returns `false`.

Note sure what you mea there, since datetimes are [considered primitives](https://github.com/sanity-io/gradient/blob/2d01bc955e043e6725902886a7afea7185f03c61/pkg/search/datamodel/key.go#L26-L27) and are equivalent in terms of comparison in these tests. Sounds like the only problem is the automatic test generation?

For geo not intersecting with itself, there is already a [test for that](https://github.com/sanity-io/groq-test-suite/pull/80/files#diff-9281d464e6eb3b49a5eb063cdc52d17e81f1f2900e73d1358396115e0bf7e1c0R47).

2024-08-09 12:11 UTC, j33ty approved these changes
LGTM

2024-08-09 12:44 UTC, merged